### ISSUE TITLE
20200913可用

### ISSUE THREAD

**Issue by 7aoZhang** [wcwac/ZZU-SCHEDULE#1]
遗憾就是没导入上课教室，想改一下代码发现正则太多了，看晕了

**Comment by wcwac** [comment]
当时上网课就忘了加教室位置了
稍等我再改改
应该可以了 你试试吧

**Comment by 7aoZhang** [comment]
> 当时上网课就忘了加教室位置了
> 稍等我再改改
> 应该可以了 你试试吧

可以了，非常好用，iOS用户狂喜
